//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_A.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer_Extras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer_Extras()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int id { get; set; }
        public int operating_system_id { get; set; }
        public int processor_id { get; set; }
        public int ram { get; set; }
        public int hdd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        public virtual Operating_Systems Operating_Systems { get; set; }
        public virtual Processor Processor { get; set; }
    }
}
