//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_A.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventoryEntities1 : DbContext
    {
        public inventoryEntities1()
            : base("name=inventoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App_Users> App_Users { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Computer_Extras> Computer_Extras { get; set; }
        public virtual DbSet<Device_Types> Device_Types { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Operating_Systems> Operating_Systems { get; set; }
        public virtual DbSet<Processor> Processors { get; set; }
        public virtual DbSet<Proyect> Proyects { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<User_Types> User_Types { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
