//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int device_type_id { get; set; }
        public Nullable<int> device_id { get; set; }
        public int state_id { get; set; }
        public int proyect_id { get; set; }
        public string responsive_number { get; set; }
        public int responsible_up_id { get; set; }
        public Nullable<int> responsible_down_id { get; set; }
        public int ticket_number_up { get; set; }
        public Nullable<int> ticket_number_down { get; set; }
        public System.DateTime create_at { get; set; }
        public Nullable<System.DateTime> edit_at { get; set; }
    
        public virtual App_Users App_Users { get; set; }
        public virtual App_Users App_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        public virtual Device_Types Device_Types { get; set; }
        public virtual Proyect Proyect { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
    }
}
