//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int id { get; set; }
        public int device_type_id { get; set; }
        public int brand_id { get; set; }
        public int model_id { get; set; }
        public int location_id { get; set; }
        public int state_id { get; set; }
        public string serial_number { get; set; }
        public string stock_number { get; set; }
        public Nullable<int> assignment_id { get; set; }
        public int proyect_id { get; set; }
        public System.DateTime create_at { get; set; }
        public string comments { get; set; }
        public int responsible_id { get; set; }
        public Nullable<int> computer_extra_id { get; set; }
    
        public virtual App_Users App_Users { get; set; }
        public virtual Assignment Assignment { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Computer_Extras Computer_Extras { get; set; }
        public virtual Device_Types Device_Types { get; set; }
        public virtual Location Location { get; set; }
        public virtual Model Model { get; set; }
        public virtual Proyect Proyect { get; set; }
        public virtual State State { get; set; }
    }
}
